import {
    SiJava,
    SiPython,
    SiTypescript,
    SiRedis,
    SiNodedotjs,
    SiPostgresql,
    SiRabbitmq,
    SiMongodb,
    SiMysql,
    SiNestjs,
    SiJunit5,
    SiSpring,
    SiFlask,
    SiPandas,
    SiApachemaven,
    SiDocker,
    SiPrisma,
    SiJupyter,
    SiAmazonaws,
    SiHeroku,
} from 'react-icons/si';
import { mySkills } from './MySkills';

export const Skills = [
    {
        slug: 'typescript',
        Component: SiTypescript,
        title: 'Typescript',
        Description: () => <>{mySkills().typescript} </>,
    },
    {
        slug: 'node',
        Component: SiNodedotjs,
        title: 'Node.js',
        Description: () => <>{mySkills().node} </>,
    },
    {
        slug: 'nest',
        Component: SiNestjs,
        title: 'Nest.js',
        Description: () => <>{mySkills().nestjs} </>,
    },
    {
        slug: 'prisma',
        Component: SiPrisma,
        title: 'Prisma',
        Description: () => <>{mySkills().prisma} </>,
    },
    {
        slug: 'java',
        Component: SiJava,
        title: 'Java',
        Description: () => <>{mySkills().java} </>,
    },
    {
        slug: 'maven',
        Component: SiApachemaven,
        title: 'Maven',
        Description: () => <>{mySkills().maven} </>,
    },
    {
        slug: 'spring',
        Component: SiSpring,
        title: 'Spring',
        Description: () => <>{mySkills().spring} </>,
    },
    {
        slug: 'junit',
        Component: SiJunit5,
        title: 'Junit',
        Description: () => <>{mySkills().junit} </>,
    },
    {
        slug: 'python',
        Component: SiPython,
        title: 'Python',
        Description: () => <>{mySkills().python} </>,
    },
    {
        slug: 'flask',
        Component: SiFlask,
        title: 'Flask',
        Description: () => <>{mySkills().flask} </>,
    },
    {
        slug: 'pandas',
        Component: SiPandas,
        title: 'Pandas',
        Description: () => <>{mySkills().pandas} </>,
    },
    {
        slug: 'jupyter',
        Component: SiJupyter,
        title: 'Jupyter',
        Description: () => <>{mySkills().jupyter} </>,
    },
    {
        slug: 'postgresql',
        Component: SiPostgresql,
        title: 'PostgreSQL',
        Description: () => <>{mySkills().postgresql} </>,
    },
    {
        slug: 'mysql',
        Component: SiMysql,
        title: 'MySQL',
        Description: () => <>{mySkills().mysql} </>,
    },
    {
        slug: 'mongo',
        Component: SiMongodb,
        title: 'MongoDB',
        Description: () => <>{mySkills().mongodb} </>,
    },
    {
        slug: 'redis',
        Component: SiRedis,
        title: 'Redis',
        Description: () => <>{mySkills().redis} </>,
    },
    {
        slug: 'rabbitmq',
        Component: SiRabbitmq,
        title: 'RabbitMQ',
        Description: () => <>{mySkills().rabbitMq} </>,
    },
    {
        slug: 'aws',
        Component: SiAmazonaws,
        title: 'AWS',
        Description: () => <>{mySkills().aws} </>,
    },
    {
        slug: 'heroku',
        Component: SiHeroku,
        title: 'Heroku',
        Description: () => <>{mySkills().heroku} </>,
    },
    {
        slug: 'docker',
        Component: SiDocker,
        title: 'Docker',
        Description: () => <>{mySkills().docker} </>,
    },
];
